version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - calc-net

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - calc-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - redis
      - rabbitmq

    networks:
      - calc-net

  consumer:
    build: ./consumer
    container_name: consumer
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
      - redis
    networks:
      - calc-net

networks:
  calc-net:
    driver: bridge