apiVersion: v1
kind: Pod
metadata:
  name: calculatrice-frontend
spec:
  containers:
  - image: mon-frontend
    name: frontend
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

