apiVersion: v1
kind: Pod
metadata:
  name: calculatrice-frontend
spec:
  containers:
  - image: mon-frontend
    name: frontend
    resources:
      requests:
        cpu: "4m"
        memory: "32Mi"
    ports:
    - containerPort: 80
      name: http
      protocol: TCP

