apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-replicaset
  namespace: moukhliss-elaramouny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"
